meta_product_name: "Moussaillon"
meta_title: "Moussaillon makers - Furniture | Oak Table | Marble | Steel"
meta_description: "Working together on the same missions for several years brought us the energy to create a furniture brand. A few months ago we started to make furnitures in our workshops near Brussels. Moussaillon is the result of that work."
meta_image: "logo_white.svg"                       # should exist in `app/assets/images/`

